import { useState } from "react";
import type { CSSProperties } from "react";

interface InsightsPanelProps {
  summary: string;
  insights?: string[];
  loading: boolean;
}

export default function InsightsPanel({ summary, insights = [], loading }: InsightsPanelProps) {
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    const text = [
      `SUMMARY:\n${summary}`,
      `\nINSIGHTS:\n${insights.map((ins, i) => `${i + 1}. ${ins}`).join("\n")}`,
    ].join("\n");
    navigator.clipboard.writeText(text).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  if (loading) {
    return (
      <div style={styles.wrapper}>
        <div style={styles.header}>
          <div style={styles.headerLeft}>
            <span style={styles.aiDot} />
            <span style={styles.title}>AI INSIGHTS</span>
          </div>
        </div>
        <div style={styles.loadingBlock}>
          <div style={styles.loadingBar} />
          <div style={{ ...styles.loadingBar, width: "75%", animationDelay: "0.2s" }} />
          <div style={{ ...styles.loadingBar, width: "60%", animationDelay: "0.4s" }} />
        </div>
      </div>
    );
  }

  if (!summary && insights.length === 0) return null;

  return (
    <div style={styles.wrapper}>
      {/* Header */}
      <div style={styles.header}>
        <div style={styles.headerLeft}>
          <span style={styles.aiDot} />
          <span style={styles.title}>AI INSIGHTS</span>
          <span style={styles.poweredBy}>powered by Claude</span>
        </div>
        <button onClick={handleCopy} style={styles.copyBtn}>
          {copied ? "✓ COPIED" : "⎘ COPY"}
        </button>
      </div>

      {/* Summary */}
      {summary && (
        <div style={styles.summaryBlock}>
          <div style={styles.summaryLabel}>SUMMARY</div>
          <p style={styles.summaryText}>{summary}</p>
        </div>
      )}

      {/* Insights list */}
      {insights.length > 0 && (
        <div style={styles.insightsList}>
          {insights.map((insight, i) => {
            const isCritical = /critical|immediate|rotate|exposed|breach/i.test(insight);
            const isWarning = /warning|recommend|consider|should|brute/i.test(insight);

            return (
              <div
                key={i}
                style={{
                  ...styles.insightCard,
                  borderLeftColor: isCritical
                    ? "#ff2d55"
                    : isWarning
                    ? "#ffd60a"
                    : "rgba(0,245,255,0.3)",
                  background: isCritical
                    ? "rgba(255,45,85,0.04)"
                    : isWarning
                    ? "rgba(255,214,10,0.04)"
                    : "rgba(0,245,255,0.03)",
                }}
              >
                <div style={styles.insightIndex}>
                  {String(i + 1).padStart(2, "0")}
                </div>
                <div style={styles.insightContent}>
                  {isCritical && <span style={styles.urgentTag}>URGENT</span>}
                  <span style={styles.insightText}>{insight}</span>
                </div>
              </div>
            );
          })}
        </div>
      )}

      {/* Footer note */}
      <div style={styles.footer}>
        ⬡ Analysis generated by Claude AI · Review findings before taking action
      </div>
    </div>
  );
}

const styles: Record<string, CSSProperties> = {
  wrapper: {
    display: "flex", flexDirection: "column", gap: "14px",
    padding: "20px",
    background: "rgba(0,245,255,0.02)",
    border: "1px solid rgba(0,245,255,0.08)",
    borderRadius: "14px",
  },
  header: {
    display: "flex", alignItems: "center",
    justifyContent: "space-between",
  },
  headerLeft: { display: "flex", alignItems: "center", gap: "10px" },
  aiDot: {
    display: "inline-block", width: "7px", height: "7px",
    borderRadius: "50%", background: "#00f5ff",
    boxShadow: "0 0 8px rgba(0,245,255,0.6)",
    animation: "pulse 2s ease-in-out infinite",
  },
  title: {
    fontFamily: "'Space Mono', monospace",
    fontSize: "11px", color: "rgba(255,255,255,0.4)",
    letterSpacing: "0.15em",
  },
  poweredBy: {
    fontSize: "10px", color: "rgba(0,245,255,0.35)",
    fontFamily: "'Space Mono', monospace",
    padding: "2px 8px",
    border: "1px solid rgba(0,245,255,0.1)",
    borderRadius: "10px",
  },
  copyBtn: {
    padding: "5px 12px",
    background: "transparent",
    border: "1px solid rgba(255,255,255,0.08)",
    borderRadius: "6px",
    color: "rgba(255,255,255,0.3)",
    fontFamily: "'Space Mono', monospace",
    fontSize: "10px", letterSpacing: "0.08em",
    cursor: "pointer", transition: "all 0.2s",
  },
  summaryBlock: {
    padding: "14px 16px",
    background: "rgba(255,255,255,0.02)",
    border: "1px solid rgba(255,255,255,0.05)",
    borderRadius: "10px",
  },
  summaryLabel: {
    fontFamily: "'Space Mono', monospace",
    fontSize: "9px", color: "rgba(255,255,255,0.25)",
    letterSpacing: "0.15em", marginBottom: "8px",
  },
  summaryText: {
    fontSize: "14px", color: "rgba(255,255,255,0.75)",
    lineHeight: "1.65", margin: 0,
  },
  insightsList: { display: "flex", flexDirection: "column", gap: "8px" },
  insightCard: {
    display: "flex", gap: "14px", alignItems: "flex-start",
    padding: "12px 14px",
    borderLeft: "2px solid",
    borderRadius: "0 8px 8px 0",
    transition: "background 0.15s",
  },
  insightIndex: {
    fontFamily: "'Space Mono', monospace",
    fontSize: "11px", color: "rgba(0,245,255,0.4)",
    minWidth: "22px", paddingTop: "1px",
  },
  insightContent: {
    display: "flex", flexDirection: "column", gap: "5px", flex: 1,
  },
  urgentTag: {
    display: "inline-block",
    fontFamily: "'Space Mono', monospace",
    fontSize: "9px", color: "#ff2d55",
    background: "rgba(255,45,85,0.1)",
    padding: "2px 6px", borderRadius: "3px",
    letterSpacing: "0.08em",
    alignSelf: "flex-start",
  },
  insightText: {
    fontSize: "13px", color: "rgba(255,255,255,0.65)",
    lineHeight: "1.55",
  },
  footer: {
    fontFamily: "'Space Mono', monospace",
    fontSize: "10px", color: "rgba(255,255,255,0.15)",
    textAlign: "center", paddingTop: "4px",
    borderTop: "1px solid rgba(255,255,255,0.04)",
    letterSpacing: "0.04em",
  },
  loadingBlock: { display: "flex", flexDirection: "column", gap: "10px", padding: "8px 0" },
  loadingBar: {
    height: "14px", width: "100%",
    background: "linear-gradient(90deg, rgba(255,255,255,0.04) 0%, rgba(255,255,255,0.08) 50%, rgba(255,255,255,0.04) 100%)",
    backgroundSize: "200% 100%",
    borderRadius: "4px",
    animation: "shimmer 1.5s infinite",
  },
};